### ISSUE TITLE
WA% in load graph!

### ISSUE THREAD

**Issue by davide1995** [LijunChang/Graph_Edit_Distance#2]
What the meaning about the warning appearing in the title?
I'm using these files
[graph_a.txt](https://github.com/LijunChang/Graph_Edit_Distance/files/2676436/graph_a.txt)
[graph_b.txt](https://github.com/LijunChang/Graph_Edit_Distance/files/2676437/graph_b.txt)

**Comment by LijunChang** [comment]
In the current implementation, the labels of vertices and edges need to be integers.

**Comment by tiankonghenlan20113046** [comment]
Hello,
I cannot find the README paper [https://lijunchang.github.io/ged.pdf.](url),could you offer a new url ?

**Comment by LijunChang** [comment]
URL corrected. Should be [https://lijunchang.github.io/pdf/ged.pdf](https://lijunchang.github.io/pdf/ged.pdf)
